### ISSUE TITLE
Propose to switch to camelCase 

### ISSUE THREAD

**Issue by demisx** [polo2ro/node-paginate-anything#6]
What do you think about changing your variables from snake_case to Javascript standard camelCase?  Looks like you are coming from a C-like programming background. I can help you to make you module more Javascript friendly. Let me know.

**Comment by polo2ro** [comment]
i have converted the variables from src/ and spec/. next i will try to add the jshint verification to the travis test to enforce format in futures version or pull requests.

**Comment by demisx** [comment]
:+1: Community loves well-organized projects.

**Comment by polo2ro** [comment]
added jshint to npm test b751d48f2835c39f049f85f982b1e63bdd52232f
